### ISSUE TITLE
Problem with irc version?

### ISSUE THREAD

**Issue by styks1111** [Herkemer/pynab-docker#3]
Looks like prebot is running into an issue with the irc module?

https://github.com/jaraco/jaraco.collections/issues/2

```
Traceback (most recent call last):
  File "/opt/pynab/prebot.py", line 20, in <module>
    import irc.bot
  File "/usr/local/lib/python3.4/dist-packages/irc/bot.py", line 22, in <module>
    from .dict import IRCDict
  File "/usr/local/lib/python3.4/dist-packages/irc/dict.py", line 4, in <module>
    from jaraco.collections import KeyTransformingDict
  File "/usr/local/lib/python3.4/dist-packages/jaraco/collections.py", line 792, in <module>
    class InstrumentedDict(six.moves.UserDict):
AttributeError: '_MovedItems' object has no attribute 'UserDict'
```

**Comment by Herkemer** [comment]
Certainly possible, but need to open up an issue in https://github.com/Murodese/pynab

**Comment by styks1111** [comment]
fixed
https://github.com/Murodese/pynab/pull/297
